from app import app, db
from models import ActivityTemplate

def seed_activities():
    """Seed the database with sample activities"""
    
    activities_data = [
        {
            'name': 'Eiffel Tower Summit Access',
            'description': 'Skip the long lines and enjoy breathtaking views from the top of the Eiffel Tower. This experience includes access to both the second floor and summit levels.',
            'category': 'sightseeing',
            'subcategory': 'landmark',
            'duration_hours': 2.0,
            'difficulty_level': 'easy',
            'cost_range_min': 25.0,
            'cost_range_max': 35.0,
            'average_cost': 30.0,
            'currency': 'EUR',
            'rating': 4.6,
            'review_count': 15234,
            'image_url': 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'outdoor',
            'best_time_of_day': 'morning',
            'age_appropriate': 'all ages',
            'group_size_min': 1,
            'group_size_max': 10,
            'booking_required': True,
            'advance_booking_days': 7,
            'what_to_bring': ['Camera', 'Comfortable shoes', 'Weather-appropriate clothing'],
            'included_items': ['Skip-the-line access', 'Summit access', 'Information guide'],
            'excluded_items': ['Food', 'Drinks', 'Transportation'],
            'tips': 'Book in advance to secure your preferred time slot. The best views are during sunset.',
            'safety_notes': 'Be aware of your surroundings and keep valuables secure. Not recommended for those with fear of heights.',
            'accessibility': 'partially accessible',
            'languages_offered': ['English', 'French', 'Spanish', 'German'],
            'popular_in_cities': [1],  # Paris
            'seasonal_availability': {'spring': 'excellent', 'summer': 'good', 'fall': 'excellent', 'winter': 'fair'},
            'weather_dependent': True
        },
        {
            'name': 'Louvre Museum Guided Tour',
            'description': 'Discover the world\'s largest art museum with an expert guide. See masterpieces including the Mona Lisa, Venus de Milo, and thousands of other treasures.',
            'category': 'culture',
            'subcategory': 'museum',
            'duration_hours': 3.0,
            'difficulty_level': 'easy',
            'cost_range_min': 45.0,
            'cost_range_max': 65.0,
            'average_cost': 55.0,
            'currency': 'EUR',
            'rating': 4.7,
            'review_count': 8921,
            'image_url': 'https://images.unsplash.com/photo-1566472237159-d6a0b9ac4ad1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'indoor',
            'best_time_of_day': 'morning',
            'age_appropriate': 'all ages',
            'group_size_min': 2,
            'group_size_max': 25,
            'booking_required': True,
            'advance_booking_days': 3,
            'what_to_bring': ['Comfortable walking shoes', 'Camera (no flash)'],
            'included_items': ['Expert guide', 'Skip-the-line access', 'Audio guide'],
            'excluded_items': ['Food', 'Drinks', 'Souvenirs'],
            'tips': 'The museum is closed on Tuesdays. Wednesday and Friday evenings are less crowded.',
            'safety_notes': 'Large crowds - keep personal belongings secure.',
            'accessibility': 'wheelchair accessible',
            'languages_offered': ['English', 'French', 'Spanish', 'Italian', 'German', 'Chinese'],
            'popular_in_cities': [1],  # Paris
            'seasonal_availability': {'spring': 'good', 'summer': 'good', 'fall': 'good', 'winter': 'excellent'},
            'weather_dependent': False
        },
        {
            'name': 'Tokyo Food Tour in Shinjuku',
            'description': 'Explore the vibrant food scene of Shinjuku with a local guide. Taste authentic Japanese street food, visit hidden izakayas, and learn about culinary traditions.',
            'category': 'food',
            'subcategory': 'food tour',
            'duration_hours': 3.5,
            'difficulty_level': 'easy',
            'cost_range_min': 60.0,
            'cost_range_max': 80.0,
            'average_cost': 70.0,
            'currency': 'USD',
            'rating': 4.8,
            'review_count': 5672,
            'image_url': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'outdoor',
            'best_time_of_day': 'evening',
            'age_appropriate': 'adults only',
            'group_size_min': 2,
            'group_size_max': 12,
            'booking_required': True,
            'advance_booking_days': 2,
            'what_to_bring': ['Comfortable walking shoes', 'Cash for additional purchases'],
            'included_items': ['Food tastings', 'Local guide', 'Cultural insights'],
            'excluded_items': ['Alcoholic beverages', 'Additional food purchases'],
            'tips': 'Come hungry! Wear comfortable shoes as you\'ll be walking and standing.',
            'safety_notes': 'Inform guide of any food allergies. Be cautious with street food if you have a sensitive stomach.',
            'accessibility': 'partially accessible',
            'languages_offered': ['English', 'Japanese'],
            'popular_in_cities': [2],  # Tokyo
            'seasonal_availability': {'spring': 'good', 'summer': 'good', 'fall': 'excellent', 'winter': 'good'},
            'weather_dependent': False
        },
        {
            'name': 'Mount Fuji Day Trip from Tokyo',
            'description': 'Escape the city and visit Japan\'s iconic Mount Fuji. Includes transportation, guided tour of the mountain area, and visit to beautiful lakes and shrines.',
            'category': 'adventure',
            'subcategory': 'nature',
            'duration_hours': 10.0,
            'difficulty_level': 'moderate',
            'cost_range_min': 120.0,
            'cost_range_max': 150.0,
            'average_cost': 135.0,
            'currency': 'USD',
            'rating': 4.5,
            'review_count': 3421,
            'image_url': 'https://images.unsplash.com/photo-1490806842075-93ac471e7f9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'outdoor',
            'best_time_of_day': 'morning',
            'age_appropriate': 'all ages',
            'group_size_min': 4,
            'group_size_max': 40,
            'booking_required': True,
            'advance_booking_days': 5,
            'what_to_bring': ['Comfortable hiking shoes', 'Warm clothing', 'Sun protection', 'Camera'],
            'included_items': ['Round-trip transportation', 'Guide', 'Lake cruise', 'Shrine visit'],
            'excluded_items': ['Lunch', 'Cable car tickets', 'Souvenirs'],
            'tips': 'Best visibility is during winter months. Bring layers as mountain weather can change quickly.',
            'safety_notes': 'Altitude may affect some visitors. Stay hydrated and follow guide instructions.',
            'accessibility': 'not accessible',
            'languages_offered': ['English', 'Japanese'],
            'popular_in_cities': [2],  # Tokyo
            'seasonal_availability': {'spring': 'fair', 'summer': 'fair', 'fall': 'good', 'winter': 'excellent'},
            'weather_dependent': True
        },
        {
            'name': 'Central Park Bike Tour',
            'description': 'Explore New York\'s iconic Central Park on a comfortable bicycle tour. Cover major landmarks, hidden gems, and learn about the park\'s history and wildlife.',
            'category': 'adventure',
            'subcategory': 'cycling',
            'duration_hours': 2.5,
            'difficulty_level': 'easy',
            'cost_range_min': 35.0,
            'cost_range_max': 50.0,
            'average_cost': 42.0,
            'currency': 'USD',
            'rating': 4.4,
            'review_count': 7893,
            'image_url': 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'outdoor',
            'best_time_of_day': 'morning',
            'age_appropriate': 'all ages',
            'group_size_min': 2,
            'group_size_max': 15,
            'booking_required': True,
            'advance_booking_days': 1,
            'what_to_bring': ['Comfortable clothes', 'Sun protection', 'Water bottle'],
            'included_items': ['Bicycle rental', 'Helmet', 'Guide', 'Map'],
            'excluded_items': ['Food', 'Drinks', 'Tips'],
            'tips': 'Morning tours are less crowded and cooler. Book early for weekend availability.',
            'safety_notes': 'Helmets must be worn. Follow traffic rules and stay with the group.',
            'accessibility': 'not accessible',
            'languages_offered': ['English', 'Spanish', 'French'],
            'popular_in_cities': [3],  # New York
            'seasonal_availability': {'spring': 'excellent', 'summer': 'good', 'fall': 'excellent', 'winter': 'fair'},
            'weather_dependent': True
        },
        {
            'name': 'Broadway Show Experience',
            'description': 'Experience the magic of Broadway with premium tickets to a top-rated show. Includes behind-the-scenes insights and dinner recommendations.',
            'category': 'entertainment',
            'subcategory': 'theater',
            'duration_hours': 3.0,
            'difficulty_level': 'easy',
            'cost_range_min': 80.0,
            'cost_range_max': 250.0,
            'average_cost': 150.0,
            'currency': 'USD',
            'rating': 4.7,
            'review_count': 12456,
            'image_url': 'https://images.unsplash.com/photo-1503095396548-78715e9c5468?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'indoor',
            'best_time_of_day': 'evening',
            'age_appropriate': 'adults only',
            'group_size_min': 1,
            'group_size_max': 8,
            'booking_required': True,
            'advance_booking_days': 14,
            'what_to_bring': ['Formal attire', 'Camera (no flash during performance)'],
            'included_items': ['Premium ticket', 'Show information', 'Dinner recommendations'],
            'excluded_items': ['Dinner', 'Drinks', 'Souvenirs'],
            'tips': 'Book well in advance for popular shows. Arrive 30 minutes early.',
            'safety_notes': 'Theater rules apply. No photography during performance.',
            'accessibility': 'wheelchair accessible',
            'languages_offered': ['English'],
            'popular_in_cities': [3],  # New York
            'seasonal_availability': {'spring': 'good', 'summer': 'good', 'fall': 'excellent', 'winter': 'excellent'},
            'weather_dependent': False
        },
        {
            'name': 'Thames River Dinner Cruise',
            'description': 'Enjoy a spectacular dinner cruise on the River Thames with stunning views of London\'s landmarks. Includes gourmet meal and live entertainment.',
            'category': 'food',
            'subcategory': 'dining cruise',
            'duration_hours': 3.5,
            'difficulty_level': 'easy',
            'cost_range_min': 75.0,
            'cost_range_max': 120.0,
            'average_cost': 95.0,
            'currency': 'GBP',
            'rating': 4.3,
            'review_count': 4532,
            'image_url': 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'both',
            'best_time_of_day': 'evening',
            'age_appropriate': 'adults only',
            'group_size_min': 2,
            'group_size_max': 6,
            'booking_required': True,
            'advance_booking_days': 7,
            'what_to_bring': ['Smart casual attire', 'Camera'],
            'included_items': ['3-course dinner', 'Live entertainment', 'Scenic views', 'Welcome drink'],
            'excluded_items': ['Additional drinks', 'Gratuities', 'Transportation'],
            'tips': 'Book window tables for best views. Dress code applies.',
            'safety_notes': 'Life jackets available. Follow crew instructions.',
            'accessibility': 'wheelchair accessible',
            'languages_offered': ['English'],
            'popular_in_cities': [4],  # London
            'seasonal_availability': {'spring': 'good', 'summer': 'excellent', 'fall': 'good', 'winter': 'fair'},
            'weather_dependent': True
        },
        {
            'name': 'Barcelona Tapas Walking Tour',
            'description': 'Discover authentic Spanish tapas culture in Barcelona\'s Gothic Quarter and El Born neighborhoods. Visit 4-5 traditional tapas bars with a local guide.',
            'category': 'food',
            'subcategory': 'food tour',
            'duration_hours': 3.0,
            'difficulty_level': 'easy',
            'cost_range_min': 55.0,
            'cost_range_max': 75.0,
            'average_cost': 65.0,
            'currency': 'EUR',
            'rating': 4.6,
            'review_count': 6234,
            'image_url': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'outdoor',
            'best_time_of_day': 'evening',
            'age_appropriate': 'all ages',
            'group_size_min': 2,
            'group_size_max': 12,
            'booking_required': True,
            'advance_booking_days': 2,
            'what_to_bring': ['Comfortable walking shoes', 'Camera'],
            'included_items': ['Tapas tastings', 'Local guide', 'Cultural commentary', 'One drink per stop'],
            'excluded_items': ['Additional drinks', 'Souvenirs', 'Transportation'],
            'tips': 'Wear comfortable shoes for cobblestone streets. Come with an appetite!',
            'safety_notes': 'Inform guide of any dietary restrictions or allergies.',
            'accessibility': 'partially accessible',
            'languages_offered': ['English', 'Spanish', 'Catalan'],
            'popular_in_cities': [5],  # Barcelona
            'seasonal_availability': {'spring': 'excellent', 'summer': 'good', 'fall': 'excellent', 'winter': 'good'},
            'weather_dependent': False
        },
        {
            'name': 'Rome Colosseum Underground Tour',
            'description': 'Explore the Colosseum\'s underground chambers and arena floor with exclusive access. Learn about gladiators and ancient Roman history.',
            'category': 'culture',
            'subcategory': 'historical site',
            'duration_hours': 3.0,
            'difficulty_level': 'moderate',
            'cost_range_min': 70.0,
            'cost_range_max': 90.0,
            'average_cost': 80.0,
            'currency': 'EUR',
            'rating': 4.8,
            'review_count': 9876,
            'image_url': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'both',
            'best_time_of_day': 'morning',
            'age_appropriate': 'all ages',
            'group_size_min': 2,
            'group_size_max': 25,
            'booking_required': True,
            'advance_booking_days': 7,
            'what_to_bring': ['Comfortable walking shoes', 'Water', 'Camera'],
            'included_items': ['Underground access', 'Arena floor access', 'Expert guide', 'Skip-the-line entry'],
            'excluded_items': ['Food', 'Drinks', 'Roman Forum access'],
            'tips': 'Book well in advance as underground tours have limited availability. Wear comfortable shoes.',
            'safety_notes': 'Uneven surfaces in underground areas. Not suitable for claustrophobic visitors.',
            'accessibility': 'not accessible',
            'languages_offered': ['English', 'Italian', 'Spanish', 'German'],
            'popular_in_cities': [6],  # Rome
            'seasonal_availability': {'spring': 'good', 'summer': 'fair', 'fall': 'excellent', 'winter': 'good'},
            'weather_dependent': False
        },
        {
            'name': 'Dubai Desert Safari',
            'description': 'Experience the Arabian desert with dune bashing, camel rides, and traditional entertainment. Includes BBQ dinner under the stars.',
            'category': 'adventure',
            'subcategory': 'desert safari',
            'duration_hours': 6.0,
            'difficulty_level': 'moderate',
            'cost_range_min': 50.0,
            'cost_range_max': 80.0,
            'average_cost': 65.0,
            'currency': 'USD',
            'rating': 4.4,
            'review_count': 8765,
            'image_url': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'outdoor',
            'best_time_of_day': 'afternoon',
            'age_appropriate': 'all ages',
            'group_size_min': 2,
            'group_size_max': 30,
            'booking_required': True,
            'advance_booking_days': 2,
            'what_to_bring': ['Sun protection', 'Camera', 'Light jacket for evening'],
            'included_items': ['4x4 safari', 'Camel ride', 'BBQ dinner', 'Entertainment', 'Hotel pickup'],
            'excluded_items': ['Alcoholic beverages', 'Quad biking', 'Sandboarding'],
            'tips': 'Best during cooler months. Bring sun protection even in winter.',
            'safety_notes': 'Not recommended for pregnant women or those with back problems. Follow safety instructions.',
            'accessibility': 'not accessible',
            'languages_offered': ['English', 'Arabic', 'German', 'French'],
            'popular_in_cities': [7],  # Dubai
            'seasonal_availability': {'spring': 'good', 'summer': 'poor', 'fall': 'excellent', 'winter': 'excellent'},
            'weather_dependent': True
        },
        {
            'name': 'Singapore Gardens by the Bay',
            'description': 'Explore the futuristic Gardens by the Bay with the iconic Supertree Grove, Cloud Forest, and Flower Dome. Includes light show at night.',
            'category': 'nature',
            'subcategory': 'garden',
            'duration_hours': 4.0,
            'difficulty_level': 'easy',
            'cost_range_min': 25.0,
            'cost_range_max': 40.0,
            'average_cost': 32.0,
            'currency': 'SGD',
            'rating': 4.5,
            'review_count': 6543,
            'image_url': 'https://images.unsplash.com/photo-1526125589963-467eca1a1675?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'location_type': 'both',
            'best_time_of_day': 'evening',
            'age_appropriate': 'all ages',
            'group_size_min': 1,
            'group_size_max': 10,
            'booking_required': False,
            'advance_booking_days': 0,
            'what_to_bring': ['Camera', 'Comfortable walking shoes', 'Light jacket for conservatories'],
            'included_items': ['Admission to conservatories', 'Garden access', 'Light show'],
            'excluded_items': ['Food', 'Drinks', 'Transportation'],
            'tips': 'Visit in the evening to see both gardens and the light show. Cloud Forest is cooler.',
            'safety_notes': 'Conservatories can be cold - bring a light jacket.',
            'accessibility': 'wheelchair accessible',
            'languages_offered': ['English', 'Chinese', 'Malay', 'Tamil'],
            'popular_in_cities': [8],  # Singapore
            'seasonal_availability': {'spring': 'good', 'summer': 'good', 'fall': 'good', 'winter': 'good'},
            'weather_dependent': False
        }
    ]
    
    with app.app_context():
        # Clear existing activities
        ActivityTemplate.query.delete()
        
        # Add new activities
        for activity_data in activities_data:
            activity = ActivityTemplate(**activity_data)
            db.session.add(activity)
        
        db.session.commit()
        print(f"Successfully seeded {len(activities_data)} activities!")

if __name__ == '__main__':
    seed_activities()
