from app import app, db
from models import Destination
from datetime import datetime

def seed_cities():
    """Seed the database with sample cities"""
    
    cities_data = [
        {
            'name': 'Paris',
            'country': 'France',
            'region': 'Europe',
            'city_type': 'city',
            'description': 'The City of Light, famous for the Eiffel Tower, Louvre Museum, and romantic atmosphere.',
            'image_url': 'https://images.unsplash.com/photo-1502602898657-3e935605a8db?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Seine River Cruise', 'Montmartre'],
            'best_time_to_visit': 'April to June, September to October',
            'average_cost': 150.0,
            'cost_index': 120.0,
            'popularity_score': 95.0,
            'rating': 4.8,
            'latitude': 48.8566,
            'longitude': 2.3522,
            'timezone': 'Europe/Paris',
            'currency': 'EUR',
            'language': 'French',
            'population': 2148000
        },
        {
            'name': 'Tokyo',
            'country': 'Japan',
            'region': 'Asia',
            'city_type': 'city',
            'description': 'A bustling metropolis blending ultra-modern technology with traditional culture.',
            'image_url': 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Senso-ji Temple', 'Tokyo Skytree', 'Shibuya Crossing', 'Tsukiji Market', 'Mount Fuji Day Trip'],
            'best_time_to_visit': 'March to May, October to November',
            'average_cost': 120.0,
            'cost_index': 110.0,
            'popularity_score': 92.0,
            'rating': 4.7,
            'latitude': 35.6762,
            'longitude': 139.6503,
            'timezone': 'Asia/Tokyo',
            'currency': 'JPY',
            'language': 'Japanese',
            'population': 37400000
        },
        {
            'name': 'New York City',
            'country': 'United States',
            'region': 'North America',
            'city_type': 'city',
            'description': 'The Big Apple - a global hub of culture, finance, and entertainment.',
            'image_url': 'https://images.unsplash.com/photo-1518391846045-559990d2d79a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Statue of Liberty', 'Central Park', 'Times Square', 'Broadway Shows', 'Empire State Building'],
            'best_time_to_visit': 'April to June, September to November',
            'average_cost': 180.0,
            'cost_index': 125.0,
            'popularity_score': 98.0,
            'rating': 4.6,
            'latitude': 40.7128,
            'longitude': -74.0060,
            'timezone': 'America/New_York',
            'currency': 'USD',
            'language': 'English',
            'population': 8336000
        },
        {
            'name': 'London',
            'country': 'United Kingdom',
            'region': 'Europe',
            'city_type': 'city',
            'description': 'Historic capital with royal palaces, world-class museums, and diverse neighborhoods.',
            'image_url': 'https://images.unsplash.com/photo-1513635263258-fb8b7b51df78?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Big Ben', 'British Museum', 'Tower of London', 'London Eye', 'Buckingham Palace'],
            'best_time_to_visit': 'May to September',
            'average_cost': 140.0,
            'cost_index': 115.0,
            'popularity_score': 90.0,
            'rating': 4.5,
            'latitude': 51.5074,
            'longitude': -0.1278,
            'timezone': 'Europe/London',
            'currency': 'GBP',
            'language': 'English',
            'population': 9648000
        },
        {
            'name': 'Barcelona',
            'country': 'Spain',
            'region': 'Europe',
            'city_type': 'city',
            'description': 'Coastal city famous for Gaudí architecture, beaches, and vibrant nightlife.',
            'image_url': 'https://images.unsplash.com/photo-1585522242455-2fc6d5636b1c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Sagrada Familia', 'Park Güell', 'La Rambla', 'Beach Barceloneta', 'Gothic Quarter'],
            'best_time_to_visit': 'May to June, September to October',
            'average_cost': 100.0,
            'cost_index': 85.0,
            'popularity_score': 88.0,
            'rating': 4.4,
            'latitude': 41.3851,
            'longitude': 2.1734,
            'timezone': 'Europe/Madrid',
            'currency': 'EUR',
            'language': 'Spanish',
            'population': 1620000
        },
        {
            'name': 'Rome',
            'country': 'Italy',
            'region': 'Europe',
            'city_type': 'city',
            'description': 'The Eternal City, home to ancient ruins, Vatican City, and incredible cuisine.',
            'image_url': 'https://images.unsplash.com/photo-1552832230-c019045e8741?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Roman Forum', 'Pantheon'],
            'best_time_to_visit': 'April to May, September to October',
            'average_cost': 110.0,
            'cost_index': 90.0,
            'popularity_score': 93.0,
            'rating': 4.6,
            'latitude': 41.9028,
            'longitude': 12.4964,
            'timezone': 'Europe/Rome',
            'currency': 'EUR',
            'language': 'Italian',
            'population': 2873000
        },
        {
            'name': 'Dubai',
            'country': 'United Arab Emirates',
            'region': 'Middle East',
            'city_type': 'city',
            'description': 'Ultra-modern desert city with stunning skyscrapers, luxury shopping, and desert adventures.',
            'image_url': 'https://images.unsplash.com/photo-1548199973-03cce0bbc87f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Burj Khalifa', 'Dubai Mall', 'Desert Safari', 'Palm Jumeirah', 'Gold Souk'],
            'best_time_to_visit': 'November to March',
            'average_cost': 130.0,
            'cost_index': 95.0,
            'popularity_score': 85.0,
            'rating': 4.3,
            'latitude': 25.2048,
            'longitude': 55.2708,
            'timezone': 'Asia/Dubai',
            'currency': 'AED',
            'language': 'Arabic',
            'population': 3331000
        },
        {
            'name': 'Singapore',
            'country': 'Singapore',
            'region': 'Asia',
            'city_type': 'city',
            'description': 'Modern city-state with futuristic architecture, diverse cuisine, and tropical gardens.',
            'image_url': 'https://images.unsplash.com/photo-1526125589963-467eca1a1675?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Chinatown', 'Universal Studios'],
            'best_time_to_visit': 'February to April',
            'average_cost': 90.0,
            'cost_index': 105.0,
            'popularity_score': 82.0,
            'rating': 4.2,
            'latitude': 1.3521,
            'longitude': 103.8198,
            'timezone': 'Asia/Singapore',
            'currency': 'SGD',
            'language': 'English',
            'population': 5850000
        },
        {
            'name': 'Amsterdam',
            'country': 'Netherlands',
            'region': 'Europe',
            'city_type': 'city',
            'description': 'Canal-lined city famous for art museums, historic architecture, and cycling culture.',
            'image_url': 'https://images.unsplash.com/photo-1554652993-71f081076c4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Anne Frank House', 'Van Gogh Museum', 'Canal Cruise', 'Vondelpark', 'Red Light District'],
            'best_time_to_visit': 'April to May, September to November',
            'average_cost': 95.0,
            'cost_index': 88.0,
            'popularity_score': 80.0,
            'rating': 4.4,
            'latitude': 52.3676,
            'longitude': 4.9041,
            'timezone': 'Europe/Amsterdam',
            'currency': 'EUR',
            'language': 'Dutch',
            'population': 872000
        },
        {
            'name': 'Sydney',
            'country': 'Australia',
            'region': 'Oceania',
            'city_type': 'city',
            'description': 'Harbor city with iconic Opera House, beautiful beaches, and outdoor lifestyle.',
            'image_url': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Sydney Opera House', 'Harbour Bridge', 'Bondi Beach', 'Royal Botanic Gardens', 'Darling Harbour'],
            'best_time_to_visit': 'September to November, March to May',
            'average_cost': 125.0,
            'cost_index': 118.0,
            'popularity_score': 87.0,
            'rating': 4.5,
            'latitude': -33.8688,
            'longitude': 151.2093,
            'timezone': 'Australia/Sydney',
            'currency': 'AUD',
            'language': 'English',
            'population': 5312000
        },
        {
            'name': 'Bangkok',
            'country': 'Thailand',
            'region': 'Asia',
            'city_type': 'city',
            'description': 'Vibrant capital with ornate temples, street food, and bustling markets.',
            'image_url': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Grand Palace', 'Wat Pho', 'Chatuchak Market', 'Street Food Tours', 'Chao Phraya River'],
            'best_time_to_visit': 'November to February',
            'average_cost': 40.0,
            'cost_index': 45.0,
            'popularity_score': 78.0,
            'rating': 4.1,
            'latitude': 13.7563,
            'longitude': 100.5018,
            'timezone': 'Asia/Bangkok',
            'currency': 'THB',
            'language': 'Thai',
            'population': 10539000
        },
        {
            'name': 'Istanbul',
            'country': 'Turkey',
            'region': 'Asia/Europe',
            'city_type': 'city',
            'description': 'Historic city bridging two continents with stunning mosques and rich culture.',
            'image_url': 'https://images.unsplash.com/photo-1524234653536-7a95b3f58f61?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
            'popular_activities': ['Hagia Sophia', 'Blue Mosque', 'Grand Bazaar', 'Bosporus Cruise', 'Topkapi Palace'],
            'best_time_to_visit': 'April to May, September to November',
            'average_cost': 60.0,
            'cost_index': 55.0,
            'popularity_score': 83.0,
            'rating': 4.3,
            'latitude': 41.0082,
            'longitude': 28.9784,
            'timezone': 'Europe/Istanbul',
            'currency': 'TRY',
            'language': 'Turkish',
            'population': 15520000
        }
    ]
    
    with app.app_context():
        # Clear existing destinations
        Destination.query.delete()
        
        # Add new cities
        for city_data in cities_data:
            city = Destination(**city_data)
            db.session.add(city)
        
        db.session.commit()
        print(f"Successfully seeded {len(cities_data)} cities!")

if __name__ == '__main__':
    seed_cities()
